export const FETCH_USERS = 'fetch_users'
export const FETCH_USER = 'fetch_user'
export const FETCH_POSTS = 'fetch_posts'
export const FETCH_ALBUMS = 'fetch_albums'
export const FETCH_COMMENTS = 'fetch_comments'
export const FETCH_PHOTOS = 'fetch_photos'

export const DELETE_POST = 'delete_post'
export const DELETE_COMMENT = 'delete_comment'
export const ADD_POST = 'add_post'
export const ADD_COMMENT = 'add_comment'
export const UPDATE_POST = 'update_post'
export const UPDATE_COMMENT = 'update_comment'

export const SET_EDITORPOST_DATA = 'set_editorpost_data'
export const SET_EDITORTITLEPOST = 'set_editor_title_post'
export const SET_EDITORBODYPOST = 'set_editor_body_post'