export const FETCH_USERS = 'fetch_users'
export const FETCH_POSTS = 'fetch_posts'
export const FETCH_ALBUMS = 'fetch_albums'
export const FETCH_COMMENTS = 'fetch_comments'
export const FETCH_PHOTOS = 'fetch_photos'

export const DELETE_POST = 'delete_post'
export const DELETE_COMMENT = 'delete_comment'
export const ADD_POST = 'delete_post'
export const ADD_COMMENT = 'delete_comment'
export const EDIT_POST = 'delete_post'
export const EDIT_COMMENT = 'delete_comment'